import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'mycogenesis',
    title: 'MycoGenesis Digital Twin',
    shortDescription: 'High-fidelity simulation and real-time morphological control of fungal computing architectures.',
    fullAbstract: 'A system for high-fidelity simulation and real-time morphological control of fungal computing architectures acting as a digital twin for a physical mycelial network. The system comprises a modeling engine for virtual representation, a signal propagation module for simulating stochastic logic and noise, and a growth-trajectory deviation engine. An adaptive steering controller generates localized correction instructions—such as thermal or nutrient modulators—to align the physical substrate\'s growth with the virtual computational topology.',
    field: 'Biological Computing / Synthetic Biology',
    tags: ['Digital Twin', 'Bio-Computing', 'Stochastic Logic', 'Control Systems'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'nelk-actuator',
    title: 'Neural Environmental Latency Kernel',
    shortDescription: 'Thermodynamically-coupled adaptive actuator control utilizing recursive neural networks.',
    fullAbstract: 'A control system for electromechanical actuators utilizing a Neural Environmental Latency Kernel (NELK) to compensate for environmental stochasticity. The system comprises an environmental sensor suite, a recursive neural network (RNN) configured to predict mechanical latency based on time-series environmental data, and an Adaptive Sliding-Mode Controller (ASMC). By modeling non-linear rheological shifts in lubricants and ohmic thermal drift, the NELK predicts actuation latency before physical manifestation.',
    field: 'Robotics / Adaptive Control',
    tags: ['RNN', 'Control Theory', 'Thermodynamics', 'Latency Prediction'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'neural-parity',
    title: 'Neural Parity-Check Loop',
    shortDescription: 'Closed-loop feedback system for maintaining BCI decoding stability via topological analysis.',
    fullAbstract: 'A closed-loop control system for maintaining stability in Brain-Computer Interfaces (BCIs). The system treats neural population dynamics as a low-dimensional latent manifold and utilizes a Neural Parity-Check Feedback Loop (NPC-FL) to mitigate representational drift. It comprises a Grassmannian tracker to monitor geometric alignment and a topological analyzer to detect ruptures in signal topology via Persistent Homology. A feedback controller adjusts neural trajectories via stochastic modulation.',
    field: 'Neural Engineering / Signal Processing',
    tags: ['BCI', 'Topology', 'Riemannian Geometry', 'Feedback Loops'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'swarm-sync',
    title: 'Neural Swarm Synchronization',
    shortDescription: 'Synchronized control of unmanned swarms using dynamic neural templates.',
    fullAbstract: 'A system for synchronized control of an unmanned swarm. A swarm state estimator calculates real-time positional entropy. A dynamic neural template generator adapts a baseline expert neural template based on this entropy. A neuro-interfacing subsystem induces the adapted template into an operator via temporal interference stimulation. A decentralized command interface maps neural phase-synchrony between the operator’s cortices to global swarm behaviors, such as coupling strength.',
    field: 'Unmanned Systems / Swarm Intelligence',
    tags: ['Swarm Intelligence', 'HCI', 'Temporal Interference', 'Entropy'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'neuro-symbolic-math',
    title: 'Neuro-Symbolic Math Engine',
    shortDescription: 'Hybrid architecture combining generative neural modules with symbolic verification kernels.',
    fullAbstract: 'A system for automated mathematical problem solving employing a neuro-symbolic hybrid architecture. It comprises a generative neural module for producing candidate solution strategies and a symbolic verification kernel (e.g., Lean 4) for validating said strategies. A refinement feedback loop iteratively provides logical inconsistency data from the symbolic kernel back to the generative module, enabling high-precision backtracking and solution convergence using Monte Carlo Tree Search.',
    field: 'Artificial Intelligence / Automated Reasoning',
    tags: ['LLM', 'Symbolic Logic', 'MCTS', 'Formal Verification'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'neuromorphic-coprocessor',
    title: 'Neuromorphic Co-Processor',
    shortDescription: 'Hardware-accelerated real-time motor vocabulary adaptation using spiking neural networks.',
    fullAbstract: 'A hardware-accelerated neuromorphic co-processor for real-time motor vocabulary adaptation. The system offloads Bayesian Vector Quantization and uncertainty calculations to a specialized SNN fabric. It includes a neural interface for asynchronous event-driven input and a structural plasticity controller that asynchronously recruits reservoir neurons to instantiate new motor primitive clusters based on Bayesian uncertainty metrics.',
    field: 'Neuromorphic Computing / BMI',
    tags: ['SNN', 'Hardware Acceleration', 'Plasticity', 'Bayesian Inference'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'mycoverse-ide',
    title: 'MycoVerse IDE',
    shortDescription: 'Integrated Development Environment for mycelial computing with physics-based digital twins.',
    fullAbstract: 'A cloud-based IDE providing a hyper-realistic, physics-based digital twin of a mycelial substrate. The system comprises a modeling engine to predict electrical signal propagation and hyphal growth. A simulation processor executes fungal computing programs within the digital twin. It features a "time-travel" debugging module for state-history replay and a predictive error module to identify deviations caused by non-linear biological growth.',
    field: 'Synthetic Biology / Software Tools',
    tags: ['IDE', 'Digital Twin', 'Simulation', 'Debugging'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'neuro-adaptive-ar',
    title: 'Neuro-Adaptive AR Target',
    shortDescription: 'AR system utilizing subconscious neural feedback for trajectory correction.',
    fullAbstract: 'A neuro-adaptive augmented reality target correction system integrating a high-fidelity BCI with dynamic AR. It captures neural oscillations to identify phase-amplitude coupling between mid-frontal theta and high-gamma bands. A neural spatial-probability field is generated and fused with kinematic state-vectors using an Unscented Kalman Filter. Trajectory warping is applied subconsciously based on parietal alpha-band power to avoid Error-Related Negativity.',
    field: 'Augmented Reality / BCI',
    tags: ['AR', 'Kalman Filter', 'Neuro-Adaptive', 'Computer Vision'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'multi-agent-patent',
    title: 'Adversarial Patent Drafter',
    shortDescription: 'Multi-agent system for automated patent drafting with sequential adversarial auditing.',
    fullAbstract: 'A system utilizing a multi-agent adversarial architecture to ensure legal defensibility and technical enablement in patent drafting. An architect agent coordinates a sequential adversarial cascade where specialized tribunal agents identify and remediate legal flaws. A quantum solver agent addresses high-complexity enablement gaps using reward-weighted tree search. Includes a technical drawing swarm for evolutionary prompt refinement.',
    field: 'Legal Tech / AI',
    tags: ['Multi-Agent', 'Adversarial', 'Patent Drafting', 'Quantum Solver'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'stochastic-fusion',
    title: 'Stochastic Fusion Engine',
    shortDescription: 'Multi-channel fusion engine for ultra-low-dose electron microscopy image reconstruction.',
    fullAbstract: 'A system for real-time ultra-low-dose electron microscopy utilizing a multi-channel stochastic fusion engine. The system employs a dual-stream neural architecture to transform secondary electron (SE) and backscattered electron (BSE) signals into a shared latent space via cross-correlation bridge layers. Stochastic inference with Monte Carlo dropout generates probability distributions for pixel intensities, enabling high-fidelity reconstruction from noisy signals.',
    field: 'Microscopy / Computer Vision',
    tags: ['Electron Microscopy', 'Stochastic Fusion', 'Neural Networks', 'Denoising'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'electromagnetic-synthesis',
    title: 'EM Field Synthesis System',
    shortDescription: 'Integrated system for advanced electromagnetic field manipulation and material synthesis.',
    fullAbstract: 'A multi-domain system for high-precision electromagnetic control. Features an interference-based masking apparatus for wireless power transfer using spatial interference arrays. Incorporates hybrid saturation-graded magnetic masks with Vanadium-Permendur cores, and high-speed SiC power modules with active quenching. Also includes a bufferless resonance kernel processor for cryogenic signal processing.',
    field: 'Electromagnetics / Materials',
    tags: ['Wireless Power', 'SiC', 'Magnetic Masks', 'Cryogenic Processing'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'mmt-vae',
    title: 'Multi-Modal Temporal VAE',
    shortDescription: 'VAE with physics-informed hierarchical latent dynamics for embodied agents.',
    fullAbstract: 'A system for multi-modal temporal representation learning in embodied agents. Utilizes modality-specific encoders for heterogeneous sensor streams and a cross-modal temporal attention module for synchronization. Features a hierarchical variational bottleneck with a macro-temporal level for global trajectory dynamics constrained by physics-informed transition modules using non-holonomic ODEs.',
    field: 'Robotics / AI',
    tags: ['VAE', 'Sensor Fusion', 'Physics-Informed', 'Latent Dynamics'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'design-balancer',
    title: 'Multi-Objective Design Balancer',
    shortDescription: 'Real-time design synthesis with differentiable manufacturing constraint layers.',
    fullAbstract: 'A system for interactive multi-objective design synthesis under manufacturing constraints. A generative design engine uses a latent space representation of a multi-physics design manifold. A differentiable manufacturing constraint layer with manifold projection operators ensures feasibility. A real-time synthesis module performs Jacobian-weighted projection to generate geometry within milliseconds.',
    field: 'Generative Design / CAD',
    tags: ['Generative Design', 'Manifold Learning', 'Manufacturing', 'Optimization'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'synthesis-planner',
    title: 'Chemical Synthesis Planner',
    shortDescription: 'AI-driven multi-objective chemical synthesis planning with Pareto front visualization.',
    fullAbstract: 'A system for multi-objective chemical synthesis planning. An AI synthesis engine generates candidate pathways which are evaluated to identify a Pareto front of non-dominated solutions considering yield, cost, emissions, and time. A visualization module renders this front as an interactive scatter plot for trade-off analysis, linked to an automated laboratory robot for execution.',
    field: 'Chemical Informatics / AI',
    tags: ['Chemical Synthesis', 'Pareto Optimization', 'AI', 'Visualization'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'co-design-engine',
    title: 'Generative Co-Design Engine',
    shortDescription: 'Simultaneous optimization of physical geometry and active control logic.',
    fullAbstract: 'A system for multi-physics generative co-design employing an AI engine to simultaneously optimize physical geometries and active control systems. Utilizing a joint design space, the engine performs concurrent updates to optimize performance metrics via high-fidelity simulations. Enables optimal spatial placement of sensors and actuators relative to the evolved physical geometry.',
    field: 'Control Systems / Design',
    tags: ['Co-Design', 'Reinforcement Learning', 'Multi-Physics', 'Control Theory'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'hierarchical-control',
    title: 'Hierarchical Predictive Control',
    shortDescription: 'Multi-scale control utilizing physics-informed VAEs and differentiable PDE solvers.',
    fullAbstract: 'A hierarchical framework for managing complex physical processes. A higher-level module uses a physics-informed VAE to generate target latent paths. A lower-level module employs a differentiable PDE solver to optimize actuator parameters, minimizing a composite objective function with a latent space conformity regularizer to ensure physical plausibility aligned with learned manifold geometry.',
    field: 'Control Systems / Physics-ML',
    tags: ['Predictive Control', 'Physics-Informed', 'PDE Solver', 'Hierarchical'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'ms-sanm',
    title: 'MS-SANM Diagnostic System',
    shortDescription: 'Non-intrusive vessel mapping using neutronic and acoustic data fusion.',
    fullAbstract: 'A system for non-intrusive diagnostic mapping of high-temperature vessels. Utilizes a dual-modal approach combining High-Energy Fast Neutron Radiography with Structural-Acoustic Wave Decomposition. A processing unit integrates neutronic attenuation data with acoustic time-of-flight measurements to solve an inverse kinetic problem, providing real-time 3D profiles of fluid density and thermal distribution.',
    field: 'Industrial Diagnostics / NDT',
    tags: ['Neutronics', 'Acoustics', 'Data Fusion', 'Non-Destructive Testing'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'legal-compiler',
    title: 'NL-to-Bytecode Compiler',
    shortDescription: 'Direct compilation of natural language business terms into smart contract bytecode.',
    fullAbstract: 'A system for compiling natural language business obligations into executable smart contract logic. A parsing engine extracts intent and logic to generate an intermediate representation. A logic synthesis module maps this to low-level VM instructions, utilizing a formal verification engine and a clause-to-opcode library to ensure security and legal compliance on distributed ledgers.',
    field: 'Blockchain / Legal Tech',
    tags: ['Smart Contracts', 'NLP', 'Compiler', 'Blockchain'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'drone-neutralization',
    title: 'STIRAP Drone Neutralization',
    shortDescription: 'Non-kinetic neutralization via Stimulated Raman Adiabatic Passage.',
    fullAbstract: 'A system for non-kinetic UAS neutralization utilizing spectrographic sensors and multi-channel lasers. Executes a Stimulated Raman Adiabatic Passage (STIRAP) protocol with a counter-intuitive pulse sequence to induce coherent population transfer from a bonding ground state to a repulsive electronic state, causing rapid structural dissociation of the target material\'s molecular matrix.',
    field: 'Defense / Photonics',
    tags: ['Directed Energy', 'STIRAP', 'Photonics', 'UAS Countermeasures'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'sub-threshold-biasing',
    title: 'Adaptive Biasing Controller',
    shortDescription: 'Non-linear biasing controller for sub-threshold CMOS logic stability.',
    fullAbstract: 'A system for modulating gate-bias currents in sub-threshold CMOS logic. Includes a differential process-monitoring circuit and transition-density estimator. An adaptive non-linear controller defines a dynamic sliding surface based on switching activity to generate modulated gate-bias current, suppressing chattering and decoupling parasitic capacitance compensation from PVT drift.',
    field: 'Semiconductors / VLSI',
    tags: ['CMOS', 'Sub-threshold', 'Adaptive Control', 'Low Power'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'phase-fod',
    title: 'Phase-Based FOD System',
    shortDescription: 'Foreign object detection for wireless power using ring-down phase analysis.',
    fullAbstract: 'A phase-based foreign object detection system for inductive power transfer. Utilizes a dual-path signal conditioning circuit and resonant tank to monitor voltage and current. A controller initiates diagnostic windows to induce ring-down oscillations, calculating Q-factor and phase-delay. A weighted fusion detection score enables high-fidelity detection of metallic objects in high-interference environments.',
    field: 'Wireless Power / Electronics',
    tags: ['FOD', 'Wireless Power', 'Signal Processing', 'Inductive Transfer'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'distributed-bci',
    title: 'Distributed Neural Decoding',
    shortDescription: 'Phase-synchronous distributed BCI architecture for saturation mitigation.',
    fullAbstract: 'A distributed neural decoding system facilitating offloading of high-dimensional neural data to edge devices during hardware saturation. A latent space decomposer splits signals into low-rank local and high-rank residual components. A phase-synchronous reintegration unit aligns remote correction vectors with the local control loop phase via DMA and shadow registers.',
    field: 'BCI / Distributed Systems',
    tags: ['BCI', 'Distributed Computing', 'Neural Decoding', 'Edge Computing'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'phonon-logic',
    title: 'Phonon-Coupled Logic',
    shortDescription: 'Logic architecture utilizing shared thermal substrates for phonon interconnects.',
    fullAbstract: 'A logic gate architecture utilizing a shared thermal medium for signal interconnection. Memristive devices on a suspended, thermally-isolated island communicate via phonon propagation. Joule heat from a primary memristor modulates the switching threshold of adjacent devices, implementing Boolean logic functions like lateral inhibition without direct electrical wiring.',
    field: 'Nanotechnology / Computing',
    tags: ['Memristors', 'Phononics', 'Logic Gates', 'Thermal Computing'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'stochastic-neuromorphic',
    title: 'Stochastic Neuromorphic CPU',
    shortDescription: 'Probabilistic computing utilizing thermal variance of polycrystalline barriers.',
    fullAbstract: 'A neuromorphic processor architecture generating hardware-intrinsic stochasticity by exploiting manufacturing variations in polycrystalline thermal barriers. Random grain boundary distributions create microscopic variations in local thermal conductivity, resulting in distinct, stochastic thermal decay rates for memristive neurons, enabling efficient Bayesian inference without dedicated PRNG circuits.',
    field: 'Neuromorphic / Hardware',
    tags: ['Stochastic Computing', 'Memristors', 'Entropy', 'Polycrystalline'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'network-targeting',
    title: 'Adaptive Network Targeting',
    shortDescription: 'Closed-loop neuromodulation with multi-node temporal interference stimulation.',
    fullAbstract: 'An adaptive closed-loop network targeting system utilizing real-time EEG for source localization. The system steers multi-node temporal interference (TI) stimulation to track non-stationary neural centroids. It generates a volumetric destructive interference null-zone to isolate target nodes and modulates TI beat frequency to reinforce synchronous oscillations within the functional network.',
    field: 'Neuromodulation / BCI',
    tags: ['Neuromodulation', 'EEG', 'Temporal Interference', 'Closed-Loop'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'co-attentive-processing',
    title: 'Co-Attentive Processor',
    shortDescription: 'Hybrid LLM-SNN feedback loop for adaptive attention modulation.',
    fullAbstract: 'A system for hybrid neural processing implementing an adaptive feedback loop between a Large Language Model (LLM) and a Spiking Neural Network (SNN) co-processor. The SNN receives encoded data from the LLM and generates temporal feedback signals based on spike-based filtering. These signals refine the LLM\'s attention weights in real-time, enabling sparse, saliency-driven processing.',
    field: 'AI / Neuromorphic',
    tags: ['LLM', 'SNN', 'Attention', 'Hybrid Architecture'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'codebook-modulation',
    title: 'Adaptive Codebook Modulation',
    shortDescription: 'Signal decoding using session-variant subspace context for codebook adaptation.',
    fullAbstract: 'A system for adaptive signal decoding utilizing session-variant signal components to modulate a fixed codebook. Input signals are decomposed into invariant and variant subspaces. The variant subspace generates a context vector via a sequence-to-vector encoder, mapping to affine transformation parameters in a FiLM layer to modulate invariant motor primitives for non-stationary environments.',
    field: 'BCI / Signal Processing',
    tags: ['Signal Processing', 'Adaptive Decoding', 'BCI', 'Deep Learning'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'cognitive-defense',
    title: 'Cognitive Warfare Defense',
    shortDescription: 'Adaptive defense against neural entrainment via null-space masking signals.',
    fullAbstract: 'An adaptive cognitive defense system utilizing endogenous rhythm detection to disrupt hostile neural entrainment. The system maps neural oscillations to a high-dimensional manifold and generates masking signals within a null-space to disrupt entrainment vectors without deviating the primary cognitive attractor state. Incorporates metabolic feedback loops and stochastic resonance.',
    field: 'Cognitive Security / Neuro-Defense',
    tags: ['Cognitive Security', 'Neural Entrainment', 'Manifold Learning', 'Defense'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'zk-resource-allocator',
    title: 'ZK-Proof Resource Allocator',
    shortDescription: 'Adaptive resource allocation for ZK-proof generation based on environmental metrics.',
    fullAbstract: 'A system for adaptive resource allocation in zero-knowledge proof generation. An adaptive scheduler dynamically calculates optimal proof aggregation thresholds based on real-time energy costs and computational metrics. It triggers proof generation only when queue thresholds are met, utilizing predictive modeling and hardware clock modulation to optimize energy efficiency.',
    field: 'Cryptography / Blockchain',
    tags: ['Zero-Knowledge Proofs', 'Resource Allocation', 'Green Computing', 'Blockchain'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'quantum-jamming-defense',
    title: 'Quantum Jamming Defense',
    shortDescription: 'Adaptive countermeasure system for quantum sensors against hostile jamming.',
    fullAbstract: 'An adaptive countermeasure system for quantum sensors employing a classification engine to distinguish hostile jamming from environmental decoherence. A controller applies physical-layer countermeasures like LO frequency adjustments and entanglement purification modifications. A reinforcement learning feedback loop refines response accuracy to enhance sensor robustness.',
    field: 'Quantum Sensing / Defense',
    tags: ['Quantum Sensing', 'Jamming', 'Countermeasures', 'Machine Learning'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'decoherence-suppression',
    title: 'Decoherence Suppression',
    shortDescription: 'Active stabilization of quantum states using real-time feedback and compensating fields.',
    fullAbstract: 'An adaptive decoherence suppression system for quantum sensors comprising a monitoring unit and feedback controller. It measures decoherence parameters via weak measurements and generates adaptive correction signals. A stabilization actuator applies compensating fields (RF, magnetic, optical) to actively suppress environmental noise, extending coherence times.',
    field: 'Quantum Metrology / Sensing',
    tags: ['Quantum Control', 'Decoherence', 'Feedback Loops', 'NV Centers'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'adaptive-digital-twin',
    title: 'Adaptive Digital Twin Control',
    shortDescription: 'Hybrid digital twin recalibration utilizing stability-constrained cGANs.',
    fullAbstract: 'A system for adaptive control utilizing a hybrid digital twin with physics-based and learned residual components. A cGAN recalibrates the residual component to address model drift. The generator is trained with a stability-regularization term derived from a Control Lyapunov Function. A stability-constrained update rule attenuates parameter shifts to maintain operational safety.',
    field: 'Industrial Control / Digital Twins',
    tags: ['Digital Twin', 'cGAN', 'Adaptive Control', 'Stability'],
    diagramType: 'network',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'microreactor-digital-twin',
    title: 'Microreactor Digital Twin',
    shortDescription: 'Real-time optimization of parallel microreactors using physics-informed neural networks.',
    fullAbstract: 'A system for high-throughput screening utilizing adaptive, physics-informed digital twins for parallel microreactor arrays. Each twin is a PINN coupling microfluidic dynamics with reaction kinetics. Real-time calibration uses composite loss functions with adaptive weighting. A global consensus model provides synergistic regularization to transfer intelligence across models.',
    field: 'Chemical Engineering / AI',
    tags: ['Microfluidics', 'PINN', 'Digital Twin', 'High-Throughput Screening'],
    diagramType: 'hierarchical',
    repoLink: '#',
    demoLink: '#'
  },
  {
    id: 'execution-throttling',
    title: 'Hardware Execution Gateway',
    shortDescription: 'FPGA-based deterministic trade throttling using market acceleration metrics.',
    fullAbstract: 'A hardware-level execution gateway for deterministic trade throttling. It dynamically modulates trade frequency based on market acceleration and pipeline occupancy. A hardware pipeline calculates second-order market derivatives to generate a scaling factor applied to physical-layer serialization delays. A phase-aligned jitter-compensation buffer manages recovery via fractional multipliers.',
    field: 'FinTech / HFT',
    tags: ['FPGA', 'High-Frequency Trading', 'Rate Limiting', 'Network Infrastructure'],
    diagramType: 'flow',
    repoLink: '#',
    demoLink: '#'
  }
];